import "./globals.css";
import { Hanken_Grotesk } from "@next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const hankenGrotesk = Hanken_Grotesk({
  weight: ["500", "700", "800"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={hankenGrotesk.className}>{children}</body>
    </html>
  );
}
